name: MacOS_CI
on:
  push:
    branches:
      - main
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  # The following one doesn't work on macos-12. It has some compiling errors related to std::date
  MacOS14_arm64_release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: |
         set -e -x
         rm -rf build
         cmake --workflow --preset macos_arm64_release_workflow
         
  MacOS14_universal2_release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: |
         set -e -x
         rm -rf build
         cmake --workflow --preset macos_universal2_release_workflow