name: Reusable Windows Build

on:
  workflow_call:
    inputs:
      job-name: # For display purposes in the reusable workflow logs
        required: true
        type: string
      runner-os: # New input for the runner OS
        required: true
        type: string
      cmake-workflow-preset:
        required: true
        type: string
      enable-codeql:
        required: false
        type: boolean
        default: false
      codeql-config-file:
        required: false
        type: string
        default: ./.github/codeql/codeql-config.yml
      codeql-sarif-output-dir:
        required: false
        type: string
        default: sarif-results

permissions:
  actions: read
  contents: read
  security-events: write # Needed if CodeQL analysis runs & uploads

jobs:
  build_and_optional_analyze:
    name: ${{ inputs.job-name }}
    runs-on: ${{ inputs.runner-os }} # Use the input for runs-on
    permissions: # Permissions moved here as they are job-specific
      actions: read
      contents: read
      security-events: write # Needed if CodeQL analysis runs & uploads

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL (if enabled)
        if: ${{ inputs.enable-codeql }}
        uses: github/codeql-action/init@v3
        with:
          config-file: ${{ inputs.codeql-config-file }}
          languages: 'cpp'

      - name: Run CMake Workflow
        run: |
          cmake --workflow --preset ${{ inputs.cmake-workflow-preset }}
        shell: cmd 

      - name: Perform CodeQL Analysis (if enabled)
        if: ${{ inputs.enable-codeql }}
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:cpp" 
          output: ${{ inputs.codeql-sarif-output-dir }} 
          upload: failure-only 

      - name: Filter SARIF (if CodeQL enabled)
        if: ${{ inputs.enable-codeql }}
        uses: advanced-security/filter-sarif@v1
        with:
          patterns: |
            +**/*.cc
            +**/*.h
            -tests/**/*.*
            -build/**/*.*
          input: ${{ inputs.codeql-sarif-output-dir }}/cpp.sarif
          output: ${{ inputs.codeql-sarif-output-dir }}/cpp.sarif.filtered 

      - name: Upload filtered SARIF (if CodeQL enabled)
        if: ${{ inputs.enable-codeql }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ inputs.codeql-sarif-output-dir }}/cpp.sarif.filtered
          category: cpp-${{ inputs.job-name }}