name: Windows_CI
on:
  push:
    branches:
      - main
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:  
  Win32_debug_no_ort:
    runs-on: windows-2022
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          config-file: ./.github/codeql/codeql-config.yml
          languages: 'cpp'
      - run: |
         cmake --workflow --preset windows_win32_debug_no_ort_workflow
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:cpp"
          output: sarif-results
          upload: failure-only
        
      - name: filter-sarif
        uses: advanced-security/filter-sarif@v1
        with:
          patterns: |
            +**/*.cc
            +**/*.h
            -tests/**/*.*
            -build/**/*.*
          input: sarif-results/cpp.sarif
          output: sarif-results/cpp.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif-results/cpp.sarif

  Win32_release_no_ort:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: |
         cmake --workflow --preset windows_win32_release_no_ort_workflow

  WinX64_debug_no_ort:
    runs-on: windows-2022
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          config-file: ./.github/codeql/codeql-config.yml
          languages: 'cpp'
      - run: |
         cmake --workflow --preset windows_x64_debug_no_ort_workflow
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:cpp"
          output: sarif-results
          upload: failure-only
        
      - name: filter-sarif
        uses: advanced-security/filter-sarif@v1
        with:
          patterns: |
            +**/*.cc
            +**/*.h
            -tests/**/*.*
            -build/**/*.*
          input: sarif-results/cpp.sarif
          output: sarif-results/cpp.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif-results/cpp.sarif

  WinX64_release_no_ort:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: |
         cmake --workflow --preset windows_x64_release_no_ort_workflow
         
  WinX64_release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: |
         cmake --workflow --preset windows_x64_release_workflow